- name : condition check
  hosts: frontend
  become: yes
  vars:
    sample_number: 15
  tasks:
  - name: Check if number is greater than 10
    ansible.builtin.debug:
      msg: "The number is greater than 10"
    when: sample_number > 10