- name: dict to list
  hosts: frontend
  vars:
    my_ips:
      - "192.168.1.1"       # Valid IPv4 address    # Valid IPv6 address
      - "255.1.1.1"         # Invalid IPv4 address (octet > 255)
      - "192.168.1.0"      # A network address      
    tags:
      ap: viskhapatanam
      hyd: telangana
      mp : mumbai
  tasks:
  - name: convert dic to list
    ansible.builtin.debug:
     msg: "the list of values are {{tags | dict2items}}"

  - name: upper case
    ansible.builtin.debug:
     msg: "upper case values are : {{tags | upper}}"

  - name: validate ip address
    ansible.builtin.debug: "{{my_ips | ansible.utils.ipaddr }}"
     