- name: dict to list
  hosts: frontend
  vars:
    my_ips:
      - "192.168.1.1"
    tags:
      ap: viskhapatanam
      hyd: telangana
      mp : mumbai
  tasks:
  - name: convert dic to list
    ansible.builtin.debug:
     msg: "the list of values are {{tags | dict2items}}"

  - name: upper case
    ansible.builtin.debug:
     msg: "upper case values are : {{tags | upper}}"

  - name: validate ip address
    ansible.builtin.debug: "{{my_ips | ansible.utils.ipaddr }}"
     