- name: error handling
  hosts: frontend
  tasks:
  - name: test errorr handling
    ansible.builtin.command: id anilkumar
    register: user_output
    ignore_errors: true

  - name: display user info
    ansible.builtin.debug:
      msg: "{{user_output}}"

  - name: display user
    ansible.builtin.command: useradd anilkumar
    when: user_output.rc != 0
