- name: error handling
  hosts: frontend
  become: yes        # 👈 VERY IMPORTANT
  gather_facts: yes

  tasks:
    - name: Check if user exists
      ansible.builtin.command: id anilkumar
      register: user_output
      ignore_errors: yes

    - name: User already exists (skip creation)
      ansible.builtin.debug:
        msg: "{{ user_output}}"

    - name: Create user
      ansible.builtin.command:
      when: user_check.rc != 0
