- name: loops
  hosts: frontend
  tasks:
  - name: looping statement
    ansible.builtin.debug:
     msg: "Hello, {{ item }}"
    loop:
      - Anil
      - Akhil
      - Aditya
      - Akash
      - Arun