- name: installing packages
  hosts: frontend
  become: yes
  tasks:
  - name: package installing using loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - Mysql
      - Postgresql
      - Redis 
      - MongoDB