- name: installing packages
  hosts: frontend
  tasks:
  - name: package installing using loop
    ansible.builtin.package:
     msg: "installing {{ item }} package"
    loop:
      - nginx
      - Mysql
      - Postgresql
      - Redis 
      - MongoDB