- name : split playbook
  hosts: frontend
  vars:
    technologies: Ansible,Docker,Kubernetes,Python,Git,Linux
  tasks:
  - name: split functions
    ansible.builtin.debug:
     msg: "technologies are {{technologies | split(',')}}"
     