- name: play level variables
  hosts: localhost
  connection: local # Ansible is connecting to localhost
  vars_files:
  - allvariables.yaml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
     msg: "details of you : {{Name}},company: {{Company}} , experience: {{Experience}} , location : {{Location}} , weight : {{Weight}}"